test:
  name: rest template
exception:
  id: 546676
fusion:
  commonExceptions:
    '1001':
        name: INVALID_EXCEPTION_DEFINITION
        title: Invalid Exception Definition
        description: Exception with code {0} is either not found or it is not defined in proper format.
    '1002':
        name: JSON_PROCESSING_EXCEPTION
        title: Unable To Process Json
        description: Something went wrong while processing json.
